# Generated by Django 3.1.1 on 2020-09-20 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_geokoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='user_id',
            new_name='uid',
        ),
    ]
